name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      
      - name: Build with Maven
        run: mvn clean package --file pom.xml -Dmaven.test.skip=true
        
        
      - name: list directories
        run: mkdir -p /tmp/persona.jar
        
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: iggatsc/tpa-persona
          tags: ${{github.run_number}}
        

      - name: Print repository name
        run: echo ${{ github.repository }}
